### ISSUE TITLE
Can't install HA using emonBase with pre-built emonSD

### ISSUE THREAD

**Issue by waako** [openenergymonitor/oem_home-assistant#1]
It downloads everything, then once it starts to clean up it throws this sort of error:

```shell
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 640, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python3/dist-packages/pip/util.py", line 529, in unzip_file
    fp.write(data)
OSError: [Errno 28] No space left on device
```

I've got nothing on the emonBase to speak off, just a few mqtt feeds coming in, so not sure why no space (and I have enabled write mode but screenshot was taken after restart):
<img width="499" alt="emonbase-space" src="https://cloud.githubusercontent.com/assets/70727/21293554/43f150d6-c528-11e6-8247-013fe01edfff.png">

Any obvious ideas? Thanks!

**Comment by glynhudson** [comment]
OpenHAB should be pre installed on the emonSD. Browse to, http  port 8080.

What version emonSD are you running?

Look for a file called 'emonSDxxx'  in /boot where xxx is the emonSD
release.



- sent from my mobile device

**Comment by waako** [comment]
Sorry I meant to say it's the latest release `emonSD-07Nov16` and didn't mean to make you respond from your mobile on a Sunday!

I was just wanting to get the Emon integration that you've worked towards up and running :)

**Comment by glynhudson** [comment]
No worries, this is what I'm here for! Trust me, I wouldn't reply if it
wasn't convenient or I didn't want to.

Any luck? OpenHAB should be all ready installed and setup so installing
yourself should not be needed if your running pre built image like you are.

Can I close this issue?

- sent from my mobile device

**Comment by waako** [comment]
Ah I now understand the confusion and why you were mentioning openHAB.

I'm trying to install Home Assistant, rather than openHAB.

Sorry I wasn't clearer

**Comment by waako** [comment]
I'm guessing it's a tmp folder issue, so will close this as not really relevant to your home-assistant info for oem.
